# Generated by Django 3.2.5 on 2021-07-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
