# Generated by Django 3.2.5 on 2021-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequenceannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sequenceannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sequenceannotation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sequenceannotation',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Seq2seqAnnotation',
        ),
        migrations.DeleteModel(
            name='SequenceAnnotation',
        ),
    ]
