# Generated by Django 3.2.5 on 2021-07-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210726_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.CreateModel(
            name='PolicyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(default='test')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='server.project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='policy_file',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.policyfile'),
        ),
    ]
