# Generated by Django 3.2.5 on 2021-07-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210726_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='policy_file',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.policyfile'),
        ),
        migrations.AlterField(
            model_name='policyfile',
            name='raw_text',
            field=models.TextField(),
        ),
    ]
