# Generated by Django 3.2.5 on 2021-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210726_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySentence',
            fields=[
                ('unique_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='政策句子序号')),
                ('example_id', models.IntegerField(verbose_name='政策序号')),
                ('sentence_id', models.IntegerField(verbose_name='句子序号')),
                ('sentence', models.TextField(null=True, verbose_name='句子文本')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySentenceTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='记录序号')),
                ('example_id', models.IntegerField(verbose_name='政策序号')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='政策句子序号')),
                ('sentence_id', models.IntegerField(verbose_name='句子序号')),
                ('sentence', models.TextField(null=True, verbose_name='句子文本')),
                ('dialogue_act', models.CharField(default='其他', max_length=128, null=True, verbose_name='句子类别')),
                ('label', models.CharField(max_length=300, null=True, verbose_name='BIO标签')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_id', models.IntegerField(verbose_name='政策序号')),
                ('text', models.TextField(null=True, verbose_name='政策原文')),
            ],
        ),
    ]
