# Generated by Django 3.2.5 on 2021-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210727_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysentencetag',
            name='reviewer',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
    ]
