# Generated by Django 3.2.5 on 2021-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_policysentencetag_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysentencetag',
            name='reviewer',
            field=models.IntegerField(verbose_name='标注者id'),
        ),
    ]
