# Generated by Django 3.2.5 on 2021-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_policysentencetag_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTagger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户序号')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('start', models.IntegerField(verbose_name='政策开始序号')),
                ('end', models.IntegerField(verbose_name='政策结束序号')),
            ],
        ),
    ]
