# Generated by Django 3.2.5 on 2021-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_policytext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytext',
            name='text',
            field=models.JSONField(default=[], null=True, verbose_name='政策原文'),
        ),
    ]
