# Generated by Django 3.2.5 on 2021-07-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_policytext_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytext',
            name='text',
        ),
    ]
