# Generated by Django 3.2.5 on 2021-07-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_policytext_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytext',
            name='text',
            field=models.JSONField(default=[], null=True, verbose_name='政策原文'),
        ),
    ]
