# Generated by Django 3.2.5 on 2021-07-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_actclass_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labelclass',
            name='id',
        ),
        migrations.AlterField(
            model_name='actclass',
            name='aid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='类别id'),
        ),
        migrations.AlterField(
            model_name='labelclass',
            name='labelid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='BIO类别'),
        ),
    ]
