# Generated by Django 3.2.5 on 2021-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210727_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='policysentencetag',
            name='permissions',
            field=models.JSONField(null=True, verbose_name='准入条件'),
        ),
    ]
