# Generated by Django 3.2.5 on 2021-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_policysentencetag_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysentencetag',
            name='unique_id',
            field=models.CharField(max_length=20, verbose_name='政策句子序号'),
        ),
    ]
