# Generated by Django 3.2.5 on 2021-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_policysentencetag_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytext',
            name='origin_policy_id',
            field=models.IntegerField(default=0, verbose_name='原序号'),
        ),
    ]
