# Generated by Django 3.2.5 on 2021-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_policytext_origin_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytext',
            name='origin_policy_id',
            field=models.IntegerField(verbose_name='原序号'),
        ),
    ]
