# Generated by Django 3.2.5 on 2021-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_policytext_origin_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytext',
            name='example_id',
            field=models.IntegerField(unique=True, verbose_name='政策序号'),
        ),
    ]
